### ISSUE TITLE
Not auto check update mods after change version from 1.9.1 to 1.11.0

### ISSUE THREAD

**Issue by daoquangdat84** [egebilecen/PZServerDiscordBot#108]
I unzipped and overwrote the files of the old version.
All works fine, except it doesn't automatically check the version of mods.
This is the error log
[pzbot.log](https://github.com/egebilecen/PZServerDiscordBot/files/13314706/pzbot.log)

---------------
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: s
Stack trace: at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at SteamWebAPI.<GetWorkshopItemDetails>d__3.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Util\SteamWebAPI.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Schedules.<>c__DisplayClass4_0.<<WorkshopItemUpdateChecker>b__0>d.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Schedules\WorkshopItemUpdateChecker.cs:line 52
Date: 10/11/2023 02:08:20 UTC
Bot Version: v1.9.1
Exception occured in ScheduleItem callback function. ScheduleItem: WorkshopItemUpdateChecker
(THIS IS AN INNER EXCEPTION, NUMBER 1)
---------------

**Comment by daoquangdat84** [comment]
this log from version 1.11.0
[pzbot (1).log](https://github.com/egebilecen/PZServerDiscordBot/files/13315130/pzbot.1.log)

**Comment by daoquangdat84** [comment]
Please help.
What can i do to fix this? now my server not auto check mods even i copy back to version 1.9.1

**Comment by egebilecen** [comment]
Hey, this error happens when steam doesn't properly respond to the request. I don't know why it happens but it's something related to the host provider regardless as request is sent from their server.
