### ISSUE TITLE
WebSocket connection was closed

### ISSUE THREAD

**Issue by maxcloutier13** [egebilecen/PZServerDiscordBot#116]
Hello. I'm having this issue when starting the PZServerDiscordbot.exe. I tried to look it up but it came out mostly as coder's trying to debug their code and I'm not exactly there in python. 

Wondering if anyone has an idea how to get this working... Thanks!

Error in psbot.log: 

Exception: System.Exception
Message: WebSocket connection was closed
Stack trace: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<WaitAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnConnectingAsync>d__114.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<ConnectAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 14-12-2023 05:29:27 UTC
Bot Version: v1.11.1
---------------

---------------
Exception: Discord.Net.WebSocketClosedException
Message: The server sent close 4014: "Disallowed intent(s)."
Stack trace: at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__34.MoveNext()
Date: 14-12-2023 05:29:27 UTC
Bot Version: v1.11.1

**Comment by egebilecen** [comment]
Hello, you have problem in intent configuration. See [here](https://github.com/egebilecen/PZServerDiscordBot/issues/106).
