### ISSUE TITLE
Error unknown

### ISSUE THREAD

**Issue by MaximusPT** [egebilecen/PZServerDiscordBot#60]
Hi egebilecen, how u doing?

In the console this message begin to appear: 

_An error occured and discord bot has been disconnected! Error details are saved into .\pzbot.log file.
Please refer to "https://github.com/egebilecen/PZServerDiscordBot/issues" and create an issue about this with the log file._

I check the log file, and then: 

---------------
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: s
Stack trace: at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at SteamWebAPI.<GetWorkshopItemDetails>d__3.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Util\SteamWebAPI.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Schedules.<>c__DisplayClass4_0.<<WorkshopItemUpdateChecker>b__0>d.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Schedules\WorkshopItemUpdateChecker.cs:line 52
Date: 19/01/2023 20:23:40 UTC
Bot Version: v1.9.0
Exception occured in ScheduleItem callback function. ScheduleItem: WorkshopItemUpdateChecker
(THIS IS AN INNER EXCEPTION, NUMBER 1)
---------------
[19/01/2023 20:23:40 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:24:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:24:41 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:25:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:25:41 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:26:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:26:41 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:27:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...

---------------
Exception: System.Exception
Message: WebSocket connection was closed
Stack trace: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 19/01/2023 20:27:18 UTC
Bot Version: v1.9.0
---------------

---------------
Exception: Discord.Net.WebSocketClosedException
Message: The server sent close 1001: "CloudFlare WebSocket proxy restarting"
Stack trace: at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__34.MoveNext()
Date: 19/01/2023 20:27:18 UTC
Bot Version: v1.9.0
---------------
[19/01/2023 20:27:41 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:28:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:28:42 UTC] WebRequest.PostAsync() - Response status code is not 200. Status code: BadRequest | URL: https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/

---------------
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: s
Stack trace: at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at SteamWebAPI.<GetWorkshopItemDetails>d__3.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Util\SteamWebAPI.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Schedules.<>c__DisplayClass4_0.<<WorkshopItemUpdateChecker>b__0>d.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Schedules\WorkshopItemUpdateChecker.cs:line 52
Date: 19/01/2023 20:28:42 UTC
Bot Version: v1.9.0
Exception occured in ScheduleItem callback function. ScheduleItem: WorkshopItemUpdateChecker
(THIS IS AN INNER EXCEPTION, NUMBER 1)
---------------
[19/01/2023 20:28:42 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...

---------------
Exception: System.Exception
Message: WebSocket connection was closed
Stack trace: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 19/01/2023 20:29:07 UTC
Bot Version: v1.9.0
---------------

---------------
Exception: System.Net.WebSockets.WebSocketException
Message: The remote party closed the WebSocket connection without completing the close handshake.
Stack trace: at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__34.MoveNext()
Date: 19/01/2023 20:29:07 UTC
Bot Version: v1.9.0
---------------
[19/01/2023 20:29:12 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:29:42 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:30:12 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:30:42 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:31:12 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[19/01/2023 20:31:42 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...

Can you see whats going on, please?

Thank you in advance :)

**Comment by egebilecen** [comment]
Hey, it’s not important. Bot just got disconnected from discord. It would try to reconnect in background, nothing to be worried about. Please supply log as attachment in future reports, thanks. :)

**Comment by MaximusPT** [comment]
ohh ok, thank you!!
