### ISSUE TITLE
There was a problem updating the mod.

### ISSUE THREAD

**Issue by cdex654** [egebilecen/PZServerDiscordBot#71]
When  mods is updated server not reboot

**Comment by egebilecen** [comment]
Hello, please provide log file.

**Comment by cdex654** [comment]
```

---------------
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: s
Stack trace: at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at SteamWebAPI.<GetWorkshopItemDetails>d__3.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Util\SteamWebAPI.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Schedules.<>c__DisplayClass4_0.<<WorkshopItemUpdateChecker>b__0>d.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Schedules\WorkshopItemUpdateChecker.cs:line 52
Date: 10/03/2023 05:32:57 UTC
Bot Version: v1.9.0
Exception occured in ScheduleItem callback function. ScheduleItem: WorkshopItemUpdateChecker
(THIS IS AN INNER EXCEPTION, NUMBER 1)
---------------
[10/03/2023 05:33:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:33:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:34:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:34:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:35:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:35:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:36:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:36:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:37:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:37:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:38:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:38:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:39:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:39:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:40:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:40:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:41:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:41:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:42:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:42:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:42:58 UTC] WebRequest.PostAsync() - Response status code is not 200. Status code: BadRequest | URL: https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/

---------------
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: s
Stack trace: at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at SteamWebAPI.<GetWorkshopItemDetails>d__3.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Util\SteamWebAPI.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Schedules.<>c__DisplayClass4_0.<<WorkshopItemUpdateChecker>b__0>d.MoveNext() in C:\Documents\Programming\C#\PZServerDiscordBot\src\Bot\Schedules\WorkshopItemUpdateChecker.cs:line 52
Date: 10/03/2023 05:42:58 UTC
Bot Version: v1.9.0
Exception occured in ScheduleItem callback function. ScheduleItem: WorkshopItemUpdateChecker
(THIS IS AN INNER EXCEPTION, NUMBER 1)
---------------
[10/03/2023 05:43:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:43:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:44:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:44:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:45:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:45:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:45:43 UTC] [PZServerCommand - initiate_restart] Caller: ⁦Cdex654⁩#2351, Params: 2
[10/03/2023 05:46:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:46:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:47:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:47:36 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:47:43 UTC] [Server Restart Schedule] Restarting server if it is running. (Is server running: True)
[10/03/2023 05:48:06 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:48:37 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:49:07 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:49:37 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:50:07 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:50:37 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:51:07 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:51:37 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:52:07 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:52:37 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[10/03/2023 05:53:00 UTC] WebRequest.PostAsync() - Response status code is not 200. Status code: BadRequest | URL: https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/
```

**Comment by egebilecen** [comment]
I believe it's just your country blacklisted by steam or maybe your host? Because requests are returning 400 Bad Request error code. Maybe try to incease workshop mod update check interval? There isn't anything I can do about it, sadly.
