### ISSUE TITLE
 How to solve the problem stop working?

### ISSUE THREAD

**Issue by cdex654** [egebilecen/PZServerDiscordBot#77]
`

[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2752895143
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2776633989
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2769995104
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2839351261
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2623458493
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2886832936
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2877551501
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2921029369
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2688676019
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2920899878
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2877607825
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2771297715
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2719592131
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2960610027
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2847449198
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2844829195
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2730975264
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2196102849
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2844315442
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2900580391
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2799152995
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2846749485
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2671890843
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 1516836158
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2463499011
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2712480036
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2917420415
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2567438952
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2698830069
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2937786633
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2767472803
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2752664795
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2832981720
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2908013174
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2932853467
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2883603166
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2941053465
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2809497084
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2846623627
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2957935793
[17/04/2023 17:29:11 UTC] SteamWebAPI.GetWorkshopItemDetails() - Workshop Item ID: 2960474000
[17/04/2023 17:29:39 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:30:09 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:30:39 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:31:10 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:31:40 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:32:10 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:32:41 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:33:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 17:33:41 UTC] [AutoServerStart Schedule] Server is not running. Attempting to start the server.

.`

This is why the server stopped working.
[17/04/2023 17:33:11 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
 How to solve the problem stop working?

**Comment by egebilecen** [comment]
Need more context about the issue you are having.

**Comment by cdex654** [comment]
`Exception: System.Exception
Message: WebSocket connection was closed
Stack trace: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 17/04/2023 18:00:36 UTC
Bot Version: v1.9.0
---------------

---------------
Exception: System.Net.WebSockets.WebSocketException
Message: The remote party closed the WebSocket connection without completing the close handshake.
Stack trace: at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__34.MoveNext()
Date: 17/04/2023 18:00:36 UTC
Bot Version: v1.9.0
---------------
[17/04/2023 18:01:01 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:01:31 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:02:02 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:02:32 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:03:02 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:03:32 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:04:02 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:04:32 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:05:03 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:05:33 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:06:03 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:06:33 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:07:03 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:07:34 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:08:04 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:08:34 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:09:04 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:09:34 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:10:05 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
[17/04/2023 18:10:35 UTC] [AutoServerStart Schedule] Either server is running or backup creator is running. Skipping...
`

**Comment by cdex654** [comment]
Server is not running when check mod finish.
